### ISSUE TITLE
failed to open port for a new instance

### ISSUE THREAD

**Issue by ohadperry** [GoogleCloudPlatform/compute-video-demo-chef#4]
hi @erjohnso , again :-)

This time, i'm trying to create a firewall rule to allow access to port 5000
I see in the [demo](https://github.com/GoogleCloudPlatform/compute-video-demo-chef/blob/master/recipes/gce-demo.rb#L59), you are using `allowed_ports` but
I don't see that attribute enabled in the firewall provider here, only `allowed`:
[link](https://github.com/chef-partners/google-compute-engine/blob/master/resources/firewall.rb#L28)

I tried

```
google_cloud_firewall "#{name_prefix}-allow-http" do
  network "default"
  allowed [5000]
...
end
```

it failed due to 
`'resource.allowed[0].IPProtocol': '5000'.  Invalid IP protocol specification.`
relevant code is [here](https://github.com/chef-partners/google-compute-engine/blob/master/providers/firewall.rb#L36)

```
allowed = []
    new_resource.allowed.each do |a|
      a.each do |k,v|
        if v.kind_of?(Array)
          p = v.flatten
        else
          p = ["#{v}"]
        end
        allowed << {"IPProtocol"=>"#{k}", "ports"=>p}
      end
    end
```

**Comment by ohadperry** [comment]
solved it by changing to 
`allowed [{"tcp" : 5000}]`

**Comment by erjohnso** [comment]
Hi @ohadpartuck - sorry to be slow to respond (again!) - glad to see you got it working!
